version: '3'
services:
  selenoid:
    image: aerokube/selenoid:1.10.9
    restart: always
    volumes:
      - "$PWD/selenoid:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "$PWD/selenoid/logs:/opt/selenoid/logs"
    command: [ "-conf", "/etc/selenoid/browsers.json", "-log-output-dir", "/opt/selenoid/logs", "-limit", "2" ]
    network_mode: bridge
    ports:
      - "4444:4444"
    depends_on:
      - selenoid-chrome-arm
  selenoid-chrome-arm:
    image: sskorol/selenoid_chromium_vnc:100.0
